// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuvS1RHLC3A2PxScSDSoa29suwb_afBJg',
    appId: '1:163922697049:web:ab0e76f6646bfbe12c8a48',
    messagingSenderId: '163922697049',
    projectId: 'chatboat-9a8f0',
    authDomain: 'chatboat-9a8f0.firebaseapp.com',
    storageBucket: 'chatboat-9a8f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_fQ_DMxIi8ujTGceZefWFaV-OwGvnU8',
    appId: '1:163922697049:android:5fc0f02ff0e409b62c8a48',
    messagingSenderId: '163922697049',
    projectId: 'chatboat-9a8f0',
    storageBucket: 'chatboat-9a8f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCiTGJVby38dKVyRZ-u1mlLl71CZ3GKUo',
    appId: '1:163922697049:ios:7de9b494fb60956e2c8a48',
    messagingSenderId: '163922697049',
    projectId: 'chatboat-9a8f0',
    storageBucket: 'chatboat-9a8f0.appspot.com',
    iosBundleId: 'com.example.chatboat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCiTGJVby38dKVyRZ-u1mlLl71CZ3GKUo',
    appId: '1:163922697049:ios:7de9b494fb60956e2c8a48',
    messagingSenderId: '163922697049',
    projectId: 'chatboat-9a8f0',
    storageBucket: 'chatboat-9a8f0.appspot.com',
    iosBundleId: 'com.example.chatboat',
  );
}
